apiVersion: v1
kind: Service
metadata:
  name: airflowapp
  labels:
    app: airflow
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: airflow
  selector:
    app: airflow
  type: NodePort
#  What is a Kubernetes NodePort service?
#  NodePorts are open ports on every cluster node. Kubernetes will route traffic that comes into a NodePort to the service,
#  even if the service is not running on that node. NodePort is intended as a foundation for other higher-level methods of
#  ingress such as load balancers and are useful in development.