---
- name: Create a directory if it does not exist
  file:
    path: /tmp/
    state: directory
    mode: '0755'
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  file:
      path: /tmp/test1
      state: absent
      mode: u=rw,g=r,o=r
  notify: create_file_Handler_No1
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  file:
      path: /tmp/test1
      state: touch
      mode: u=rw,g=r,o=r
  notify: create_file_Handler_No1
- name: line insert
  lineinfile:
      path: /tmp/test1
      line: 'Hello world!'
      insertbefore: BOF
  notify: echo_txt_to_file_Handler_No2
