
# apiVersion - Kubernetes API version
# kind - the type of object you want to create
# metadata - info about the object so that it can be uniquely identified
# spec - desired state of the object
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  appdeploy
  labels:
    app: superset
spec:
  selector:
    matchLabels:
      app: superset
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: amancevice/superset
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
