---
  - name: Install Vim
    apt: name=vim state=present
    when: ansible_os_family == "Debian"
    notify: install_Handler_No1
  - name: Install zip
    apt: name=zip state=present
    when: ansible_os_family == "Debian"
    notify: install_Handler_No1
  - name: Install unzip
    apt: name=zip state=present
    when: ansible_os_family == "Debian"
    notify: Uninstall_Handler_No2
  - name: Uinsatll zip
    apt: name=zip state=absent
    notify: Uninstall_Handler_No2
  - name: Uninstall unzip
    apt: name=unzip state=absent
    notify: Uninstall_Handler_No2
  - name: Uninstall Vim
    apt: name=vim state=absent
    notify: Uninstall_Handler_No2


