---
- name: What is my ansible_hostname
  debug:
    msg: ansible_hostname = {{ ansible_hostname }}
- name: Create a directory if it does not exist
  file:
    path: /tmp/
    state: directory
    mode: '0755'
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  file:
      path: /tmp/test2
      state: absent
      mode: u=rw,g=r,o=r
  notify: create_file_Handler_No1
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  file:
      path: /tmp/test2
      state: touch
      mode: u=rw,g=r,o=r
  notify: create_file_Handler_No1
- name: line insert
  lineinfile:
      path: /tmp/test2
      line: 'This Servers hostname is:{{ ansible_hostname }}'
      insertbefore: BOF
  notify: echo_txt_to_file_Handler_No2

